// SPDX-FileCopyrightText: 2026 Mat McGowan
// SPDX-License-Identifier: MIT

#include <stdio.h>
#include "esp_sleep.h"
#include "ulp_riscv.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

// ULP binary symbols (generated by the ULP build)
extern const uint8_t ulp_main_bin_start[] asm("_binary_ulp_main_bin_start");
extern const uint8_t ulp_main_bin_end[] asm("_binary_ulp_main_bin_end");

// Second ULP binary
extern const uint8_t ulp_sensor_bin_start[] asm("_binary_ulp_sensor_bin_start");
extern const uint8_t ulp_sensor_bin_end[] asm("_binary_ulp_sensor_bin_end");

// ULP shared variables — from generated headers
extern "C" {
#include "ulp_main.h"
#include "ulp_sensor.h"
}

extern "C" void app_main(void) {
    // Load first ULP binary
    esp_err_t err = ulp_riscv_load_binary(ulp_main_bin_start,
        (ulp_main_bin_end - ulp_main_bin_start));
    printf("ULP main loaded: %s\n", esp_err_to_name(err));

    // Reference ULP symbols to verify linkage
    printf("ULP app_state: %lu\n", (unsigned long)ulp_app_state);
    printf("Sensor value: %lu, count: %lu\n",
        (unsigned long)sensor_sensor_value,
        (unsigned long)sensor_sensor_count);

    // Start the ULP
    err = ulp_riscv_run();
    printf("ULP started: %s\n", esp_err_to_name(err));

    while (1) {
        printf("ULP app_state: %lu\n", (unsigned long)ulp_app_state);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
