[env:esp32c6-lp-interrupt]
platform = espressif32@55.3.36
framework = espidf
board = esp32-c6-devkitc-1
extra_scripts = pre:../../scripts/pio_ulp_cmake.py
board_build.ulp_projects =
    lp_core_main:ulp
