// SPDX-FileCopyrightText: 2026 Mat McGowan
// SPDX-License-Identifier: MIT
//
// On-device tests for ULP binary loading and shared variable updates.

#include <doctest.h>
#include <Arduino.h>
#include <esp_sleep.h>
#include <ulp_riscv.h>

// ULP binary symbols (generated by the ULP build)
extern const uint8_t ulp_main_bin_start[] asm("_binary_ulp_main_bin_start");
extern const uint8_t ulp_main_bin_end[] asm("_binary_ulp_main_bin_end");

extern const uint8_t ulp_sensor_bin_start[] asm("_binary_ulp_sensor_bin_start");
extern const uint8_t ulp_sensor_bin_end[] asm("_binary_ulp_sensor_bin_end");

// ULP shared variables — from generated headers
extern "C" {
#include "ulp_main.h"
#include "ulp_sensor.h"
}

TEST_SUITE("ULP Load") {

TEST_CASE("ULP main binary loads" * doctest::timeout(10)) {
    esp_err_t err = ulp_riscv_load_binary(ulp_main_bin_start,
        ulp_main_bin_end - ulp_main_bin_start);
    CHECK(err == ESP_OK);
}

TEST_CASE("ULP main runs and updates app_state" * doctest::timeout(10)) {
    esp_err_t err = ulp_riscv_load_binary(ulp_main_bin_start,
        ulp_main_bin_end - ulp_main_bin_start);
    REQUIRE(err == ESP_OK);

    // app_state starts at 0 before ULP runs
    ulp_app_state = 0;

    err = ulp_riscv_run();
    REQUIRE(err == ESP_OK);

    // Give the ULP time to execute
    delay(100);

    Serial.printf("ulp_app_state: %lu\n", (unsigned long)ulp_app_state);
    CHECK(ulp_app_state != 0);
}

TEST_CASE("ULP sensor increments count" * doctest::timeout(10)) {
    esp_err_t err = ulp_riscv_load_binary(ulp_sensor_bin_start,
        ulp_sensor_bin_end - ulp_sensor_bin_start);
    REQUIRE(err == ESP_OK);

    // Reset shared variables
    sensor_sensor_count = 0;
    sensor_sensor_value = 0;

    err = ulp_riscv_run();
    REQUIRE(err == ESP_OK);

    delay(100);

    Serial.printf("sensor_count: %lu, sensor_value: %lu\n",
        (unsigned long)sensor_sensor_count,
        (unsigned long)sensor_sensor_value);
    CHECK(sensor_sensor_count > 0);
    CHECK(sensor_sensor_value > 0);
}

}
